import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/context/AuthContext";
import { tripsService } from "@/services/trips";
import { toast } from "sonner";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { Navigate } from "react-router-dom";
import {
  MapPin, Calendar, Users, DollarSign, FileText, Plus, Trash2,
  Plane, ChevronRight, Sparkles, Clock, Lightbulb, Hotel, Car, Compass
} from "lucide-react";
import AttractionSearchDialog from "@/components/trips/AttractionSearchDialog";
import HotelSearchDialog from "@/components/trips/HotelSearchDialog";
import TransportSearchDialog from "@/components/trips/TransportSearchDialog";
import { Hotel as HotelType } from "@/services/hotels";
import { TransportService as TransportType } from "@/services/transport";
import { Attraction as AttractionType } from "@/services/destinations";

interface ItineraryDay {
  dayNumber: number;
  activities: Activity[];
  notes: string;
}

interface Activity {
  id: string;
  time: string;
  title: string;
  type: "attraction" | "hotel" | "transport" | "food" | "other";
  price?: number;
}

const activityTypes = [
  { value: "attraction", label: "Attraction", color: "bg-emerald-100 text-emerald-700" },
  { value: "hotel", label: "Hotel", color: "bg-blue-100 text-blue-700" },
  { value: "transport", label: "Transport", color: "bg-orange-100 text-orange-700" },
  { value: "food", label: "Food", color: "bg-rose-100 text-rose-700" },
  { value: "other", label: "Other", color: "bg-gray-100 text-gray-700" },
];

const ghanaDestinations = [
  "Cape Coast", "Accra", "Kumasi", "Elmina", "Kakum National Park",
  "Mole National Park", "Tamale", "Boti Falls", "Wli Waterfalls",
  "Labadi Beach", "Busua Beach", "Paga", "Bolgatanga", "Ho",
];

const suggestedItineraries: Record<string, { day: number; activities: string[] }[]> = {
  "Cape Coast": [
    { day: 1, activities: ["Arrive & check into hotel", "Visit Cape Coast Castle", "Sunset walk along the beach"] },
    { day: 2, activities: ["Kakum National Park canopy walk", "Traditional lunch at local restaurant", "Evening at Fort William"] },
    { day: 3, activities: ["Visit Elmina Castle", "Local market shopping", "Depart"] },
  ],
  "Kumasi": [
    { day: 1, activities: ["Visit Manhyia Palace Museum", "Explore Kejetia Market", "Ashanti Cultural Centre"] },
    { day: 2, activities: ["Lake Bosomtwe", "Craft village tour", "Kente weaving workshop"] },
  ],
};

export default function PlanTrip() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { isAuthenticated, isLoading } = useAuth();

  const [step, setStep] = useState(1);
  const [tripName, setTripName] = useState("");
  const [destination, setDestination] = useState(searchParams.get("destination") || "");
  const [description, setDescription] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [travellers, setTravellers] = useState("1");
  const [budget, setBudget] = useState("");
  const [days, setDays] = useState<ItineraryDay[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(false);

  const numDays = () => {
    if (startDate && endDate) {
      const diff = new Date(endDate).getTime() - new Date(startDate).getTime();
      return Math.max(1, Math.ceil(diff / (1000 * 60 * 60 * 24)) + 1);
    }
    return 0;
  };

  const autoGenerateDays = () => {
    const n = numDays();
    if (n <= 0) { toast.error("Select valid dates first"); return; }
    const startDt = new Date(startDate);
    const newDays: ItineraryDay[] = Array.from({ length: n }, (_, i) => {
      const date = new Date(startDt);
      date.setDate(startDt.getDate() + i);
      return { dayNumber: i + 1, activities: [], notes: "" };
    });
    setDays(newDays);
    toast.success(`Generated ${n}-day itinerary`);
  };

  const applySuggestedItinerary = () => {
    const suggestion = suggestedItineraries[destination];
    if (!suggestion) { toast.error("No suggestions for this destination yet"); return; }
    const newDays: ItineraryDay[] = suggestion.map((s) => ({
      dayNumber: s.day,
      activities: s.activities.map((a, idx) => ({
        id: `${s.day}-${idx}`, time: "", title: a, type: "other" as const,
      })),
      notes: "",
    }));
    setDays(newDays);
    toast.success("Suggested itinerary applied!");
  };

  const addActivity = (dayNumber: number) => {
    setDays(days.map((d) =>
      d.dayNumber === dayNumber
        ? { ...d, activities: [...d.activities, { id: `${Date.now()}`, time: "", title: "", type: "other" }] }
        : d
    ));
  };

  const updateActivity = (dayNumber: number, actId: string, field: keyof Activity, value: string) => {
    setDays(days.map((d) =>
      d.dayNumber === dayNumber
        ? { ...d, activities: d.activities.map((a) => a.id === actId ? { ...a, [field]: value } : a) }
        : d
    ));
  };

  const removeActivity = (dayNumber: number, actId: string) => {
    setDays(days.map((d) =>
      d.dayNumber === dayNumber
        ? { ...d, activities: d.activities.filter((a) => a.id !== actId) }
        : d
    ));
  };

  const removeDay = (dayNumber: number) => {
    setDays(days.filter((d) => d.dayNumber !== dayNumber));
  };

  const addDay = () => {
    const next = days.length > 0 ? Math.max(...days.map((d) => d.dayNumber)) + 1 : 1;
    setDays([...days, { dayNumber: next, activities: [], notes: "" }]);
  };

  const updateDayNotes = (dayNumber: number, notes: string) => {
    setDays(days.map((d) => d.dayNumber === dayNumber ? { ...d, notes } : d));
  };

  const handleSelectHotel = (dayNumber: number, hotel: HotelType) => {
    setDays(days.map((d) =>
      d.dayNumber === dayNumber
        ? {
          ...d,
          activities: [
            ...d.activities,
            {
              id: `${Date.now()}`,
              time: "Check-in",
              title: `Stay at ${hotel.name} (${hotel.location})`,
              type: "hotel",
              price: hotel.price_per_night
            }
          ]
        }
        : d
    ));
    toast.success(`Added ${hotel.name} to Day ${dayNumber}`);
  };

  const handleSelectTransport = (dayNumber: number, transport: TransportType) => {
    setDays(days.map((d) =>
      d.dayNumber === dayNumber
        ? {
          ...d,
          activities: [
            ...d.activities,
            {
              id: `${Date.now()}`,
              time: transport.departure_time || "",
              title: `${transport.type.toUpperCase()}: ${transport.operator} (${transport.from_location} to ${transport.to_location})`,
              type: "transport",
              price: transport.price
            }
          ]
        }
        : d
    ));
    toast.success(`Added ${transport.type} to Day ${dayNumber}`);
  };

  const handleSelectAttraction = (dayNumber: number, attraction: AttractionType) => {
    setDays(days.map((d) =>
      d.dayNumber === dayNumber
        ? {
          ...d,
          activities: [
            ...d.activities,
            {
              id: `${Date.now()}`,
              time: attraction.opening_hours.split("-")[0].trim() || "Morning",
              title: attraction.name,
              type: "attraction",
              price: attraction.entrance_fee.toLowerCase().includes("free") ? 0 : parseFloat(attraction.entrance_fee.replace(/[^0-9.]/g, '')) || 0
            }
          ]
        }
        : d
    ));
    toast.success(`Added ${attraction.name} to Day ${dayNumber}`);
  };

  const calculateTotalCost = () => {
    return days.reduce((total, day) => {
      return total + day.activities.reduce((dayTotal, act) => dayTotal + (act.price || 0), 0);
    }, 0);
  };

  const handleSubmit = async () => {
    if (!destination || !startDate || !endDate) {
      toast.error("Please complete all required fields");
      return;
    }
    setIsSubmitting(true);
    try {
      // Build activities as a combined string per day for backend
      const trip = await tripsService.createTrip(
        destination,
        startDate,
        endDate,
        description || tripName || undefined,
        budget ? parseFloat(budget) : undefined
      );

      for (const day of days) {
        const activitiesText = day.activities.map((a) => `[${a.type.toUpperCase()}] ${a.time ? a.time + ": " : ""}${a.title}`).join("\n");
        if (activitiesText || day.notes) {
          await tripsService.addItinerary(trip.id, day.dayNumber, activitiesText || undefined, day.notes || undefined);
        }
      }
      toast.success("🎉 Trip planned successfully!");
      navigate(`/trips/${trip.id}`);
    } catch (err: any) {
      toast.error(err.message || "Failed to create trip");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (isLoading) {
    return (
      <DashboardLayout role="user">
        <div className="flex items-center justify-center h-64">
          <div className="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent" />
        </div>
      </DashboardLayout>
    );
  }

  if (!isAuthenticated) return <Navigate to="/login" />;

  const steps = [
    { num: 1, label: "Trip Details" },
    { num: 2, label: "Itinerary" },
    { num: 3, label: "Review & Save" },
  ];

  return (
    <DashboardLayout role="user">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary">
              <Plane className="h-5 w-5" />
            </div>
            <div>
              <h1 className="font-display text-2xl font-bold">Plan Your Trip</h1>
              <p className="text-sm text-muted-foreground">Create your Ghana adventure, step by step</p>
            </div>
          </div>

          {/* Step progress */}
          <div className="flex items-center gap-2 mt-6">
            {steps.map((s, i) => (
              <div key={s.num} className="flex items-center gap-2">
                <button
                  onClick={() => step > s.num && setStep(s.num)}
                  className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold transition-all ${step === s.num ? "bg-primary text-white shadow-md" :
                    step > s.num ? "bg-emerald-500 text-white cursor-pointer" : "bg-muted text-muted-foreground"
                    }`}
                >
                  {step > s.num ? "✓" : s.num}
                </button>
                <span className={`text-sm font-medium hidden sm:block ${step === s.num ? "text-foreground" : "text-muted-foreground"}`}>{s.label}</span>
                {i < steps.length - 1 && <ChevronRight className="h-4 w-4 text-muted-foreground mx-1" />}
              </div>
            ))}
          </div>
        </div>

        {/* ── Step 1: Trip Details ────────────────────── */}
        {step === 1 && (
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2"><FileText className="h-5 w-5 text-primary" /> Trip Information</CardTitle>
                <CardDescription>Give your trip a name and basic details</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="block text-sm font-medium mb-1.5">Trip Name <span className="text-muted-foreground">(optional)</span></label>
                  <Input placeholder="e.g., Cape Coast Adventure, Christmas Holiday..." value={tripName} onChange={(e) => setTripName(e.target.value)} />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1.5">Destination <span className="text-destructive">*</span></label>
                  <div className="relative">
                    <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <Input
                      className="pl-9"
                      placeholder="e.g., Cape Coast, Kumasi..."
                      value={destination}
                      onChange={(e) => setDestination(e.target.value)}
                      list="destinations-list"
                      required
                    />
                    <datalist id="destinations-list">
                      {ghanaDestinations.map((d) => <option key={d} value={d} />)}
                    </datalist>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1.5">Description / Notes</label>
                  <Textarea placeholder="What's the purpose of your trip? Any personal goals or notes..." value={description} onChange={(e) => setDescription(e.target.value)} rows={3} />
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2"><Calendar className="h-5 w-5 text-primary" /> Travel Dates & Budget</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-1.5">Start Date <span className="text-destructive">*</span></label>
                    <Input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} required min={new Date().toISOString().split("T")[0]} />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-1.5">End Date <span className="text-destructive">*</span></label>
                    <Input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} required min={startDate || new Date().toISOString().split("T")[0]} />
                  </div>
                </div>
                {startDate && endDate && numDays() > 0 && (
                  <div className="flex items-center gap-2 rounded-lg border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-primary">
                    <Clock className="h-4 w-4" />
                    <strong>{numDays()} days</strong> &nbsp;·&nbsp; {new Date(startDate).toLocaleDateString("en-GB", { day: "numeric", month: "short" })} – {new Date(endDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
                  </div>
                )}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-1.5"><Users className="inline h-3.5 w-3.5 mr-1" /> Number of Travellers</label>
                    <Input type="number" min="1" max="50" value={travellers} onChange={(e) => setTravellers(e.target.value)} />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-1.5"><DollarSign className="inline h-3.5 w-3.5 mr-1" /> Total Budget (GH₵)</label>
                    <Input type="number" placeholder="0.00" value={budget} onChange={(e) => setBudget(e.target.value)} step="0.01" min="0" />
                  </div>
                </div>
                {budget && travellers && parseInt(travellers) > 1 && (
                  <div className="rounded-lg border border-border bg-muted/50 p-3 text-sm">
                    Per person budget: <strong className="text-primary">GH₵ {(parseFloat(budget) / parseInt(travellers)).toFixed(2)}</strong>
                  </div>
                )}
              </CardContent>
            </Card>

            <Button
              className="w-full h-12 text-base gap-2"
              onClick={() => {
                if (!destination || !startDate || !endDate) {
                  toast.error("Please fill in destination and dates");
                  return;
                }
                setStep(2);
              }}
            >
              Continue to Itinerary <ChevronRight className="h-5 w-5" />
            </Button>
          </div>
        )}

        {/* ── Step 2: Itinerary Builder ─────────────── */}
        {step === 2 && (
          <div className="space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <h2 className="font-display text-xl font-bold">Build Your Itinerary</h2>
                <p className="text-sm text-muted-foreground">{destination} · {numDays()} days</p>
              </div>
              <div className="flex gap-2">
                {days.length === 0 && (
                  <Button variant="outline" size="sm" onClick={autoGenerateDays} className="gap-2">
                    <Sparkles className="h-4 w-4" />
                    Auto-Generate
                  </Button>
                )}
                {suggestedItineraries[destination] && (
                  <Button variant="outline" size="sm" onClick={applySuggestedItinerary} className="gap-2">
                    <Lightbulb className="h-4 w-4" />
                    Use Suggestions
                  </Button>
                )}
                <Button size="sm" onClick={addDay} className="gap-2">
                  <Plus className="h-4 w-4" /> Add Day
                </Button>
              </div>
            </div>

            {days.length === 0 ? (
              <Card className="border-dashed">
                <CardContent className="py-16 text-center">
                  <Calendar className="h-12 w-12 text-muted-foreground mx-auto mb-4 opacity-40" />
                  <h3 className="font-semibold mb-1">No days planned yet</h3>
                  <p className="text-sm text-muted-foreground mb-4">Click "Auto-Generate" to create a day layout based on your dates, or add days manually.</p>
                  <Button onClick={autoGenerateDays} className="gap-2"><Sparkles className="h-4 w-4" /> Auto-Generate Days</Button>
                </CardContent>
              </Card>
            ) : (
              <div className="space-y-4">
                {days.map((day, di) => {
                  const date = startDate ? new Date(startDate) : null;
                  if (date) date.setDate(date.getDate() + (day.dayNumber - 1));
                  return (
                    <Card key={day.dayNumber} className="overflow-hidden">
                      <CardHeader className="pb-3 bg-gradient-to-r from-primary/5 to-transparent">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            <div className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-white text-sm font-bold">
                              {day.dayNumber}
                            </div>
                            <div>
                              <CardTitle className="text-base">Day {day.dayNumber}</CardTitle>
                              {date && <p className="text-xs text-muted-foreground">{date.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" })}</p>}
                            </div>
                          </div>
                          <Button variant="ghost" size="sm" onClick={() => removeDay(day.dayNumber)} className="text-muted-foreground hover:text-destructive">
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </CardHeader>
                      <CardContent className="pt-4 space-y-3">
                        {/* Activities */}
                        {day.activities.length > 0 && (
                          <div className="space-y-2">
                            {day.activities.map((act) => (
                              <div key={act.id} className="flex items-center gap-2 rounded-lg border border-border bg-muted/30 p-2">
                                <Input
                                  placeholder="Time (e.g. 9:00 AM)"
                                  value={act.time}
                                  onChange={(e) => updateActivity(day.dayNumber, act.id, "time", e.target.value)}
                                  className="w-28 text-xs border-0 bg-transparent p-0 h-auto focus-visible:ring-0"
                                />
                                <span className="text-muted-foreground">|</span>
                                <div className="flex-1 min-w-0">
                                  <Input
                                    placeholder="Activity name..."
                                    value={act.title}
                                    onChange={(e) => updateActivity(day.dayNumber, act.id, "title", e.target.value)}
                                    className="border-0 bg-transparent p-0 h-auto focus-visible:ring-0 text-sm w-full truncate"
                                  />
                                </div>
                                {act.price && (
                                  <div className="text-[10px] font-bold text-emerald-600 px-1.5 py-0.5 bg-emerald-50 rounded border border-emerald-100 shrink-0">
                                    GH₵ {act.price}
                                  </div>
                                )}
                                <select
                                  value={act.type}
                                  onChange={(e) => updateActivity(day.dayNumber, act.id, "type", e.target.value)}
                                  className="rounded-full px-2 py-0.5 text-xs border border-border bg-background"
                                >
                                  {activityTypes.map((t) => <option key={t.value} value={t.value}>{t.label}</option>)}
                                </select>
                                <button onClick={() => removeActivity(day.dayNumber, act.id)} className="text-muted-foreground hover:text-destructive">
                                  <Trash2 className="h-3.5 w-3.5" />
                                </button>
                              </div>
                            ))}
                          </div>
                        )}
                        <div className="grid grid-cols-1 sm:grid-cols-4 gap-2">
                          <Button variant="outline" size="sm" onClick={() => addActivity(day.dayNumber)} className="gap-1.5 text-xs border-dashed">
                            <Plus className="h-3.5 w-3.5" /> Manual
                          </Button>
                          <AttractionSearchDialog
                            defaultLocation={destination}
                            onSelect={(attr) => handleSelectAttraction(day.dayNumber, attr)}
                            trigger={
                              <Button variant="outline" size="sm" className="gap-1.5 text-xs border-dashed text-emerald-600 hover:text-emerald-700 hover:bg-emerald-50">
                                <Compass className="h-3.5 w-3.5" /> Attraction
                              </Button>
                            }
                          />
                          <HotelSearchDialog
                            defaultLocation={destination}
                            onSelect={(hotel) => handleSelectHotel(day.dayNumber, hotel)}
                            trigger={
                              <Button variant="outline" size="sm" className="gap-1.5 text-xs border-dashed text-blue-600 hover:text-blue-700 hover:bg-blue-50">
                                <Hotel className="h-3.5 w-3.5" /> Find Hotel
                              </Button>
                            }
                          />
                          <TransportSearchDialog
                            defaultTo={destination}
                            onSelect={(transport) => handleSelectTransport(day.dayNumber, transport)}
                            trigger={
                              <Button variant="outline" size="sm" className="gap-1.5 text-xs border-dashed text-orange-600 hover:text-orange-700 hover:bg-orange-50">
                                <Car className="h-3.5 w-3.5" /> Find Transport
                              </Button>
                            }
                          />
                        </div>
                        <div>
                          <label className="text-xs text-muted-foreground block mb-1">Day Notes</label>
                          <Textarea
                            placeholder="Any special notes for this day..."
                            value={day.notes}
                            onChange={(e) => updateDayNotes(day.dayNumber, e.target.value)}
                            rows={2}
                            className="text-sm"
                          />
                        </div>
                      </CardContent>
                    </Card>
                  );
                })}
              </div>
            )}

            <div className="flex gap-3">
              <Button variant="outline" onClick={() => setStep(1)}>← Back</Button>
              <Button className="flex-1 gap-2" onClick={() => setStep(3)}>
                Review Trip <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          </div>
        )}

        {/* ── Step 3: Review ────────────────────────── */}
        {step === 3 && (
          <div className="space-y-6">
            <h2 className="font-display text-xl font-bold">Review Your Trip</h2>

            {/* Summary card */}
            <Card className="border-primary/20 bg-gradient-to-br from-primary/5 to-transparent">
              <CardContent className="pt-6">
                <div className="flex items-start gap-4">
                  <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary text-white">
                    <Plane className="h-7 w-7" />
                  </div>
                  <div className="flex-1">
                    <h3 className="font-display text-xl font-bold">{tripName || destination}</h3>
                    {tripName && <p className="text-sm text-muted-foreground">{destination}</p>}
                    <div className="flex flex-wrap gap-4 mt-3 text-sm">
                      <div className="flex items-center gap-1.5 text-muted-foreground">
                        <Calendar className="h-4 w-4" />
                        {new Date(startDate).toLocaleDateString("en-GB", { day: "numeric", month: "short" })} – {new Date(endDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
                      </div>
                      <div className="flex items-center gap-1.5 text-muted-foreground">
                        <Users className="h-4 w-4" />
                        {travellers} traveller{parseInt(travellers) > 1 ? "s" : ""}
                      </div>
                      <div className="flex items-center gap-1.5 text-muted-foreground">
                        <Clock className="h-4 w-4" />
                        {numDays()} days
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4 mt-4 bg-white/50 rounded-xl p-3 border border-primary/10">
                      <div>
                        <p className="text-[10px] uppercase tracking-wider text-muted-foreground font-bold mb-1">Set Budget</p>
                        <p className={`text-lg font-bold ${budget ? "text-primary" : "text-muted-foreground italic"}`}>
                          {budget ? `GH₵ ${parseFloat(budget).toLocaleString()}` : "Not set"}
                        </p>
                      </div>
                      <div>
                        <p className="text-[10px] uppercase tracking-wider text-muted-foreground font-bold mb-1">Estimated Cost</p>
                        <p className="text-lg font-bold text-emerald-600">
                          GH₵ {calculateTotalCost().toLocaleString()}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Itinerary summary */}
            {days.length > 0 && (
              <Card>
                <CardHeader><CardTitle className="text-base">Itinerary Summary</CardTitle></CardHeader>
                <CardContent className="space-y-3">
                  {days.map((day) => (
                    <div key={day.dayNumber} className="flex gap-3">
                      <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary text-xs font-bold mt-0.5">
                        {day.dayNumber}
                      </div>
                      <div className="flex-1">
                        <div className="flex flex-wrap gap-1.5">
                          {day.activities.length > 0 ? day.activities.map((a) => {
                            const typeInfo = activityTypes.find((t) => t.value === a.type);
                            return (
                              <div key={a.id} className="flex items-center gap-1">
                                <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${typeInfo?.color || "bg-gray-100"}`}>{a.title || "(Unnamed)"}</span>
                              </div>
                            );
                          }) : <span className="text-sm text-muted-foreground">No activities planned</span>}
                        </div>
                        {day.notes && <p className="text-xs text-muted-foreground mt-1">{day.notes}</p>}
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>
            )}

            {description && (
              <Card>
                <CardContent className="pt-4">
                  <p className="text-sm text-muted-foreground italic">"{description}"</p>
                </CardContent>
              </Card>
            )}

            <div className="flex gap-3">
              <Button variant="outline" onClick={() => setStep(2)}>← Back</Button>
              <Button className="flex-1 h-12 text-base gap-2" onClick={handleSubmit} disabled={isSubmitting}>
                {isSubmitting ? (
                  <><div className="h-4 w-4 rounded-full border-2 border-white border-t-transparent animate-spin" /> Saving...</>
                ) : (
                  <><Plane className="h-5 w-5" /> Save My Trip</>
                )}
              </Button>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
